# Generated by Django 3.1.7 on 2021-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210430_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
