# Generated by Django 3.1.7 on 2021-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210505_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
