# Generated by Django 3.1.7 on 2021-05-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210505_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccount',
            name='card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
