# Generated by Django 3.1.7 on 2021-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_memberaccount_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
