# Generated by Django 3.1.7 on 2021-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20210518_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='card_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
