# Generated by Django 3.1.7 on 2021-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210524_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='card_id',
            field=models.CharField(default='0000000000000000', max_length=255),
        ),
    ]
