# Generated by Django 3.1.7 on 2021-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210526_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaccount',
            name='card_id',
            field=models.CharField(default='0000000000000000', max_length=255),
        ),
    ]
