# Generated by Django 3.1.7 on 2021-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar.png', null=True, upload_to=''),
        ),
    ]
