# Generated by Django 3.1.7 on 2021-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210524_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
