# Generated by Django 3.1.7 on 2021-03-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210325_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
