# Generated by Django 3.1.7 on 2021-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
    ]
