# Generated by Django 3.1.7 on 2021-04-06 14:28

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210406_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Date of publication'),
        ),
    ]
