# Generated by Django 3.1.7 on 2021-03-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210331_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='userprof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.userprofile'),
        ),
    ]
